apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    environment: testing
    project: tech-sharing
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 1000m
          memory: 1000Mi
        limits:
          cpu: 1000m
          memory: 1000Mi