apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
  - name: "http"
    port: 8080
    targetPort: 80
